### ISSUE TITLE
Please keep the builds clean

### ISSUE THREAD

**Issue by nnWhisperer** [facebookincubator/hsthrift#135]
Hello,
Thank you for the great work. I appreciate this treasure project. I tried and did manage to build it myself, after spending some time but, for a project of this importance I believe that there must be an easy way to get started without fighting against the build errors.
Looking at the commits, the main branch build seems to be failing for the last 2 months.
Thank you

**Comment by simonmar** [comment]
Thanks for the feedback. We do actually have an internal CI process that ensures the build works, the issue with the github CI I think is that it is failing with the old gcc version in the base Ubuntu image we're using for CI, so we need to update the base Ubuntu image (in the same way we recently did with Glean). If you're using a recent Linux install with a newer gcc it should work.

I'll keep the issue open until we've updated the CI. Let us know if you have any other issues with the build.
