### ISSUE TITLE
hs deprecated in Apache Thrift, hsthrift viable alternative?

### ISSUE THREAD

**Issue by tscholak** [facebookincubator/hsthrift#23]
Hi, this commit sent me here: https://github.com/apache/thrift/commit/b51a62b9686bad1db949735025ca6823c3c8462b

We are using Apache Thrift for communication between a Python client and a Haskell server, and I am wondering if hsthrift is mature enough to replace Apache Thrift.

I'd appreciate some guidance on the matter.

Thank you!

**Comment by simonmar** [comment]
You would need to use fbthrift on both the server and the client, because the wire format is different, but otherwise yes, hsthrift is much more mature and stable than the Haskell support in Apache Thrift.
