### ISSUE TITLE
How to obtain Cabal 3.6.0.0

### ISSUE THREAD

**Issue by tscholak** [facebookincubator/hsthrift#34]
Hi, following #23, I've started today to look into using `hsthrift`. Unfortunately, all projects in this repository depend on `cabal-version: 3.6`, and I do not know how to install this unreleased version of Cabal. It would help me if you could share the Dockerfile for https://github.com/orgs/facebookincubator/packages/container/package/hsthrift%2Fci-base, because this image has it installed. Thanks.

**Comment by tscholak** [comment]
nvm, I think I found it, https://github.com/facebookincubator/hsthrift/blob/b71b8199ea65934b2a63db4f1c7a19bfe9cb16f6/.github/workflows/ci.yml

**Comment by zsol** [comment]
Hey @tscholak glad you found the dockerfile. Feel free to reopen if you bump into further issues getting Cabal 3.6 set up
